name: Bug Report
description: Report a bugs
title: '[Bug] '
labels: ['🐞 Bug']
body:
    - type: markdown
      attributes:
          value: |
              Thanks for taking the time to fill out this bug report!
    - type: input
      id: contact
      attributes:
          label: Contact Details
          description: How can we get in touch with you if we need more info?
          placeholder: ex. email@example.com
      validations:
          required: false
    - type: textarea
      id: what-happened
      attributes:
          label: What happened?
          description: Also tell us, what did you expect to happen?
          placeholder: Tell us what you see!
          value: 'A bug happened!'
      validations:
          required: true
    - type: dropdown
      id: node-version
      attributes:
          label: Node version
          description: What node version are you running?
          options:
              - '16.x'
              - '17.x'
      validations:
          required: true
    - type: dropdown
      id: pkg-man
      attributes:
          label: Package manager
          description: What package manager are you using?
          options:
              - 'yarn'
              - 'npm'
              - 'pnpm'
      validations:
          required: true
    - type: textarea
      attributes:
          label: Environment used
          description: |
              Examples:
                - **OS**: Arch
                - **Node**: 16.13.0
          value: |
              - **OS**:
              - **Node**:
          render: 'Markdown'
      validations:
          required: true
    - type: textarea
      id: logs
      attributes:
          label: Relevant log output
          description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
          render: 'Shell'
    - type: checkboxes
      id: terms
      attributes:
          label: Code of Conduct
          description: By submitting this issue, you agree to follow our [Code of Conduct](https://example.com)
          options:
              - label: I agree to follow this project's Code of Conduct
                required: true
