name: Feature Request
description: Request for an feature(s)
title: '[Feature Request] '
labels: ['🈸 Feature Request']
body:
    - type: checkboxes
      attributes:
          label: Is there an existing issue for this?
          description: Please search to see if an issue already exists for the feature you requested.
          options:
              - label: I have searched the existing issues
                required: true
    - type: textarea
      attributes:
          label: Requested Feature
          description: Description of Requested Feature. Explain the feature and expected result if you can.
          render: 'Markdown'
      validations:
          required: true
    - type: textarea
      attributes:
          label: Reasons
          description: Reasons why this feature(s) must be added or why you requesting for this feature.
          render: 'Markdown'
      validations:
          required: true
    - type: textarea
      attributes:
          label: Environment used
          description: |
              Examples:
                - **OS**: Arch
                - **Node**: 16.13.0
                - **Yarn**: 1.22.17
          value: |
              - OS:
              - Node:
              - npm:
          render: 'Markdown'
      validations:
          required: true
    - type: textarea
      attributes:
          label: Anything else?
          description: |
              Links? References? Anything that will give us more context about the feature you are requested!

              Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
          render: 'Markdown'
      validations:
          required: false
